project:
  type: website
  output-dir: docs

website:
  search:
    location: navbar
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  title: "Jonathan Templin's Website"
  page-footer:
    left: |
      © $\infty$, Jonathan Templin
    right: |
      [Source on GitHub](https://github.com/jonathantemplin/website)
  navbar:
    collapse-below: md
    collapse: true
    tools-collapse: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: files/cv_jtemplin.pdf
        text: CV
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: archived-courses.qmd
        text: Course Archive
      - href: dcmbook.qmd
        text: DCM Book

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual
